TravelTracker/Models/Destination.cs
using System.Collections.Generic;

namespace TravelTracker.Models
{
  public class Destination
  {
    public Destination()
    {
      this.Trips = new HashSet<Trip>();
    }

    public int DestinationId { get; set; }
    public string CityName { get; set; }
    public virtual ICollection<Trip> Trips { get; set; }
  }
}

TravelTracker/Controllers/DestinationsController.cs
using Microsoft.AspNetCore.Mvc;
using TravelTracker.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace TravelTracker.Controllers
{
  public class DestinationsController : Controller
  {
    private readonly TravelTrackerContext _db;

    public DestinationsController(TravelTrackerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Destination> model = _db.Destinations.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Destination destination)
    {
      _db.Destinations.Add(destination);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDestination = _db.Destinations
        .Include(destination => destination.Trips)
        .ThenInclude(join => join.Traveller)
        // .ThenInclude(join => join.Club)
        .FirstOrDefault(destination => destination.DestinationId == id);
      return View(thisDestination);
    }

    public ActionResult Edit(int id)
    {
      var thisDestination = _db.Destinations.FirstOrDefault(destinations => destinations.DestinationId == id);
      return View(thisDestination);
    }

    [HttpPost]
    public ActionResult Edit(Destination destination)
    {
      _db.Entry(destination).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDestination = _db.Destinations.FirstOrDefault(destination => destination.DestinationId == id);
      return View(thisDestination);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDestination = _db.Destinations.FirstOrDefault(destination => destination.DestinationId == id);
      _db.Destinations.Remove(thisDestination);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TravelTracker/Controllers/TravellersController.cs
using Microsoft.AspNetCore.Mvc;
using TravelTracker.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace TravelTracker.Controllers
{
  public class TravellersController : Controller
  {
    private readonly TravelTrackerContext _db;

    public TravellersController(TravelTrackerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Traveller> model = _db.Travellers.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      ViewBag.DestinationId = new SelectList(_db.Destinations, "DestinationId", "CityName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Traveller traveller)
    {
      _db.Travellers.Add(traveller);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTraveller = _db.Travellers
        .Include(traveller => traveller.Trips)
        .ThenInclude(join => join.Destination)
        // .ThenInclude(join => join.Club)
        .FirstOrDefault(traveller => traveller.TravellerId == id);
      return View(thisTraveller);
    }

    public ActionResult Edit(int id)
    {
      var thisTraveller = _db.Travellers.FirstOrDefault(travellers => travellers.TravellerId == id);
      return View(thisTraveller);
    }

    [HttpPost]
    public ActionResult Edit(Traveller traveller)
    {
      _db.Entry(traveller).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTraveller = _db.Travellers.FirstOrDefault(traveller => traveller.TravellerId == id);
      return View(thisTraveller);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTraveller = _db.Travellers.FirstOrDefault(traveller => traveller.TravellerId == id);
      _db.Travellers.Remove(thisTraveller);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TravelTracker/Controllers/TripsController.cs
using Microsoft.AspNetCore.Mvc;
using TravelTracker.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace TravelTracker.Controllers
{
  public class TripsController : Controller
  {
    private readonly TravelTrackerContext _db;

    public TripsController(TravelTrackerContext db)
    {
      _db = db;
    }

    public ActionResult Create()
    {
      return View();
    }

    public ActionResult SoloCreate()
    {
      ViewBag.TravellerId = new SelectList(_db.Travellers, "TravellerId", "Name");
      ViewBag.DestinationId = new SelectList(_db.Destinations, "DestinationId", "CityName");
      return View();
    }

    public ActionResult GroupCreate()
    {
      ViewBag.ClubId = new SelectList(_db.Clubs, "ClubId", "Name");
      ViewBag.DestinationId = new SelectList(_db.Destinations, "DestinationId", "CityName");
      return View();
    }

    [HttpPost]
    public ActionResult SoloCreate(Trip trip)
    {
      _db.Trips.Add(trip);
      _db.SaveChanges();
      return RedirectToAction("Index", "Destinations");
    }

    [HttpPost]
    public ActionResult GroupCreate(Trip trip)
    {
      _db.Trips.Add(trip);
      _db.SaveChanges();
      return RedirectToAction("Index", "Destinations");
    }

    public ActionResult Edit(int id)
    {
      var joinEntry = _db.Trips.FirstOrDefault(entry => entry.TripId == id);
      return View(joinEntry);
    }

    [HttpPost]
    public ActionResult Edit(Trip trip)
    {
      _db.Entry(trip).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }

    public ActionResult Delete(int id)
    {
      var joinEntry = _db.Trips.FirstOrDefault(entry => entry.TripId == id);
      return View(joinEntry);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var joinEntry = _db.Trips.FirstOrDefault(entry => entry.TripId == id);
      _db.Trips.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
  }
}

TravelTracker/Views/Destinations/AddTraveller.cshtml
@{
  Layout = "_Layout";
}

@model TravelTracker.Models.Destination
<h1>@Html.Label($"Add a Traveller for {Model.CityName}")</h1>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DestinationId)
  <div class="form-group">
    @Html.Label("Select Traveller")
    @Html.DropDownList("TravellerId", null, new { @class="form-control"})
  </div>
  <div class="form-group">
    <label for="startDate">Start of Visit</label>
    <input type="date" name="startDate" id="startDate" class="form-control" required=true />
  </div>
  <div class="form-group">
    <label for="endDate">End of Visit</label>
    <input type="date" name="endDate" id="endDate" class="form-control" required=true />
  </div>
  <input type="submit" value="Add new Traveller" class="btn btn-outline-dark"/>
}
<hr />
<h5>@Html.ActionLink("Back to Destination Details", "Details", new { id = Model.DestinationId })</h5>

TravelTracker/Views/Destinations/Create.cshtml
@{
  Layout = "_Layout";
}

@model TravelTracker.Models.Destination

<h3>Add a new Destination</h3>
<hr />
@using (@Html.BeginForm())
{
  <div class="form-group">
    @Html.Label("City Name")
    @Html.TextBoxFor(model => model.CityName, new {@class="form-control"})
  </div>
  <input type="submit" value="Add a new Destination" class="btn btn-outline-dark">
}
<hr />
<h5>@Html.ActionLink("Show all Destinations", "Index")</h5>

TravelTracker/Views/Destinations/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TravelTracker.Models.Destination

<h3>@Html.Label($"Are you sure you want to delete {Model.CityName}?")</h3>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-outline-dark">
}
<hr />
<h5>@Html.ActionLink("Back to Destinations", "Index")</h5>

TravelTracker/Views/Destinations/Details.cshtml
@{
  Layout = "_Layout";
}

@model TravelTracker.Models.Destination

<h3>@Html.Label($"{Model.CityName} Details")</h3>
<hr />

@if (@Model.Trips.Count == 0)
{
  <h3>No Travellers have Visited this Destination!</h3>
}
else
{
  <h5>Visited By</h5>
  @foreach(var join in Model.Trips)
  {
    <h3>@Html.ActionLink($"{join.Traveller.Name}", "Details", "Travellers", new { id = join.Traveller.TravellerId })</h3>
    <h5>@Html.Label(join.StartDate.ToString("MMMM d, yyyy")) - @Html.Label(join.EndDate.ToString("MMMM d, yyyy"))</h5>
    <h5>@Html.ActionLink("Edit", "Edit", "Trips", new { id = join.TripId}) | @Html.ActionLink("Delete", "Delete", "Trips", new {id = join.TripId })</h5>
  }
}
<hr/>
<h5>@Html.ActionLink("Edit Destination", "Edit", new { id = Model.DestinationId })</h5>
<h5>@Html.ActionLink("Remove Destination", "Delete", new { id = Model.DestinationId })</h5>

TravelTracker/Views/Destinations/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TravelTracker.Models.Destination

<h3>@Html.Label($"Edit {Model.CityName}")</h3>
<hr />
@using (@Html.BeginForm())
{
  @Html.HiddenFor(model => model.DestinationId)
  <div class="form-group">
    @Html.Label("City Name")
    @Html.TextBoxFor(model => model.CityName, new {@class="form-control"})
  </div>
  <input type="submit" value="Edit Destination" class="btn btn-outline-dark">
}
<hr />
<h5>@Html.ActionLink("Show all Destinations", "Index")</h5>

TravelTracker/Views/Destinations/Index.cshtml
@{
  Layout = "_Layout";
}

@using TravelTracker.Models;
@model List<TravelTracker.Models.Destination>;

<h3>Destinations</h3>
<hr/>
@if (@Model.Count == 0)
{
  <h3>No Destinations Have Been Added Yet!</h3>
}

@foreach (Destination destination in Model)
{
  <h3>@Html.ActionLink($"{destination.CityName}", "Details", new { id = destination.DestinationId })</h3>
}
<hr />
<h5>@Html.ActionLink("Add a new Destination", "Create")</h5>